#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

RubyVM::YJIT.enable if defined?(RubyVM::YJIT) && !RubyVM::YJIT.enabled?

require "badline"
require "badline/gui"

autostart = !ARGV.delete("--no-autostart")
media_path = ARGV[0] if ARGV[0] && File.exist?(ARGV[0])

Badline::GUI::Application.new(media_path:, autostart:).run
