#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "optparse"

options = { autostart: true, jit: true }

parser = OptionParser.new do |opts|
  opts.banner = <<~BANNER
    Usage: badline [options] [media]

    Media can be a .prg/.p00 program, a .d64/.d71/.d81 disk image,
    a .crt cartridge, or a directory to mount as device 8.

    Options:
  BANNER

  opts.on("--no-autostart", "Boot to READY. instead of running the program") do
    options[:autostart] = false
  end

  opts.on("--disable-jit", "Run without enabling YJIT") do
    options[:jit] = false
  end

  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => e
  warn "badline: #{e.message}"
  warn "Try 'badline --help' for more information."
  exit 1
end

media_path = ARGV[0]
if media_path && !File.exist?(media_path)
  warn "badline: no such file or directory: #{media_path}"
  exit 1
end

jit_available = defined?(RubyVM::YJIT) && !RubyVM::YJIT.enabled?
RubyVM::YJIT.enable if options[:jit] && jit_available

require "badline"
require "badline/gui"

Badline::GUI::Application.new(media_path:, autostart: options[:autostart]).run
